# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: '166cb359-82c9-4b69-a2f9-68a2b086358d'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'my-rs-group'
    location: 'West Central US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/Azure/azure-docs-json-samples/master/get-started-deployment/linked-template/azuredeploy.json'
    overrideParameters: '-projectName arm-pipeline'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'